import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import PageTransition from "./components/PageTransition/PageTransition";
import ScrollToTop from "./components/ScrollToTop/ScrollToTop";
import SmoothScrollProvider from "./components/SmoothScrollProvider/SmoothScrollProvider";
import { ThemeProvider } from "./components/ThemeProvider/ThemeProvider";
import { verifyUser, simplifyUser } from "./utils/auth-utils";
import ServiceStatus from "./components/ServiceStatus/ServiceStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRecord = await verifyUser();
  const simpleUser = simplifyUser(userRecord);
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ backgroundColor: 'var(--background)' }}>
        <ThemeProvider>
          <SmoothScrollProvider ease={0.1}>
            <NavBar serverUser={simpleUser} />
            <ServiceStatus />
            <PageTransition type="slide-up" duration={0.4}>
              {children}
            </PageTransition>
            <ScrollToTop />
          </SmoothScrollProvider>
        </ThemeProvider>
        {/* Global viewport blur at bottom */}
        <div className="telescope-vignette" aria-hidden="true"></div>
      </body>
    </html>
  );
}
