import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import PageTransition from "./components/PageTransition/PageTransition";
import { ThemeProvider } from "./components/ThemeProvider/ThemeProvider";
import { verifyUser, simplifyUser } from "./utils/auth-utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRecord = await verifyUser();
  const simpleUser = simplifyUser(userRecord);
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <NavBar serverUser={simpleUser} />
          <PageTransition type="slide-up" duration={0.4}>
            {children}
          </PageTransition>
        </ThemeProvider>
      </body>
    </html>
  );
}
