import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import PageTransition from "./components/PageTransition/PageTransition";
import ScrollToTop from "./components/ScrollToTop/ScrollToTop";
import SmoothScrollProvider from "./components/SmoothScrollProvider/SmoothScrollProvider";
import { ThemeProvider } from "./components/ThemeProvider/ThemeProvider";
import { verifyUser, simplifyUser } from "./utils/auth-utils";
import ServiceStatus from "./components/ServiceStatus/ServiceStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRecord = await verifyUser();
  const simpleUser = simplifyUser(userRecord);
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ backgroundColor: 'var(--background)' }}>
        <ThemeProvider>
          <SmoothScrollProvider ease={0.1}>
            <NavBar serverUser={simpleUser} />
            <ServiceStatus />
            <PageTransition type="fade" duration={0.75}>
              {children}
            </PageTransition>
            <ScrollToTop />
          </SmoothScrollProvider>
        </ThemeProvider>
        {/* Global black fade overlay for route transitions */}
        <div id="global-fade" style={{position:'fixed',inset:0,background:'#000',opacity:0,pointerEvents:'none',transition:'opacity 360ms ease',zIndex:1000}} />
        <script dangerouslySetInnerHTML={{__html:`(function(){
          var fade=document.getElementById('global-fade');
          function fadeOut(){ if(!fade) return; fade.style.opacity='1'; fade.style.pointerEvents='auto'; }
          function fadeIn(){ if(!fade) return; fade.style.opacity='0'; fade.style.pointerEvents='none'; }
          window.__fadeToBlack = fadeOut; window.__fadeFromBlack = fadeIn;
          // On page show, ensure we fade in from black if coming from a transition
          if(document.visibilityState==='visible'){ fadeIn(); }
          window.addEventListener('pageshow',fadeIn);
        })();`}} />
        {/* Global viewport blur at bottom */}
        <div className="telescope-outer" aria-hidden="true">
          <div className="telescope-vignette" />
        </div>
      </body>
    </html>
  );
}
